# Generated by Django 3.2.5 on 2021-07-14 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=200)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
