version: "3"

services:

    customerapp:
        build: .
        entrypoint: ["./wait.sh"]
        volumes:
            - ./:/var/www
        ports:
            - "8001:8001"
        depends_on: 
            - customerapp-mysql
            - customerapp-redis
    
    customerapp-mysql:
        image: mysql:8.0.21
        
        restart: always
        ports:
            - "3306"
        volumes:
            - ./.docker/dbdata:/docker-entrypoint-customer-initdb.d/:ro
        environment: 
            MYSQL_DATABASE: customerapp
            MYSQL_ROOT_PASSWORD: root
    
    customerapp-redis:
        image: redis:alpine
        expose: 
            - 6379