# Generated by Django 3.2.5 on 2021-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
