# Generated by Django 3.2.5 on 2021-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_return_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
