version: "3"

services:

    rentalapp:
        build: .
        entrypoint: ["./wait.sh"]
        volumes:
            - ./:/var/www
        ports:
            - "8002:8002"
        depends_on: 
            - rentalapp-mysql
            - rentalapp-redis
    
    rentalapp-mysql:
        image: mysql:8.0.21
        restart: always
        ports:
            - "3306"
        volumes:
            - ./.docker/dbdata:/docker-entrypoint-rentalapp-initdb.d/:ro
        environment: 
            MYSQL_DATABASE: rentalapp
            MYSQL_ROOT_PASSWORD: root
    
    rentalapp-redis:
        image: redis:alpine
        expose: 
            - 6379