# Generated by Django 3.2.5 on 2021-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qtd_available', models.IntegerField(blank=True, default=1, null=True)),
                ('qtd_total', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
