version: "3"

services:

    productapp:
        build: .
        entrypoint: ["./wait.sh"]
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on: 
            - productapp-mysql
            - productapp-redis
    
    productapp-mysql:
        image: mysql:8.0.21
        
        restart: always
        ports:
            - "30000:3306"
        volumes:
            - ./.docker/dbdata:/docker-entrypoint-product-initdb.d/:ro
        environment: 
            MYSQL_DATABASE: productapp
            MYSQL_ROOT_PASSWORD: root
    
    productapp-redis:
        image: redis:alpine
        expose: 
            - 6379


networks:
    default:
        name: jornada-network